name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Elm
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/

      - name: Make index.html
        run: |
          elm make --optimize src/Main.elm

      - name: Make data.json
        run: |
          wget https://github.com/bronze1man/yaml2json/releases/download/v1.3/yaml2json_linux_amd64
          chmod +x yaml2json_linux_amd64
          ./yaml2json_linux_amd64 < data.yml > data.json
          rm yaml2json_linux_amd64

      - name: Move files
        run: |
          mkdir ./public
          mv ./data.json ./public/
          mv ./index.html ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: britishfrog.com
